"""india-inequality — interactive demo.

Two tabs:
1. Inequality toolkit — upload a CSV (or use the bundled synthetic example)
   and get Gini, Lorenz curve, percentile shares, Palma ratio.
2. Wealth composition simulator — see how asset *allocation* (not income)
   drives long-run household wealth.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from india_inequality import inequality as ineq
from india_inequality import wealth

st.set_page_config(page_title="India Wealth Inequality Toolkit", page_icon="📊", layout="wide")

st.title("📊 India Wealth Inequality Toolkit")
st.caption(
    "A reusable toolkit for inequality measurement, plus the household "
    "wealth-composition simulator from the author's research on wealth "
    "accumulation in India. **Demonstration using synthetic data by "
    "default** — upload your own CSV for real analysis."
)

tab_ineq, tab_wealth = st.tabs(["Inequality measures", "Wealth composition simulator"])

with tab_ineq:
    st.subheader("Upload a distribution, or use the synthetic example")
    uploaded = st.file_uploader("CSV with one numeric column of income/wealth values", type="csv")
    example_path = Path(__file__).resolve().parents[1] / "data" / "synthetic_household_wealth.csv"

    if uploaded is not None:
        df = pd.read_csv(uploaded)
        st.info("Using your uploaded data.")
    else:
        df = pd.read_csv(example_path)
        st.warning(
            "⚠️ **Demonstration mode**: this is a clearly-labelled SYNTHETIC "
            "household net-worth distribution (lognormal body + Pareto tail), "
            "generated by `examples/generate_synthetic_wealth.py`. It is "
            "**not** real survey data — upload your own CSV above for an "
            "empirical result."
        )

    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if not numeric_cols:
        st.error("No numeric columns found in this file.")
        st.stop()
    col = st.selectbox("Column to analyse", numeric_cols, index=len(numeric_cols) - 1)
    values = df[col].dropna().values

    try:
        summary = ineq.summary_table(values)
    except ValueError as exc:
        st.error(str(exc))
        st.stop()

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Gini coefficient", f"{summary['gini'][0]:.3f}")
    c2.metric("Top 10% share", f"{summary['top_10_share'][0]:.1%}")
    c3.metric("Bottom 50% share", f"{summary['bottom_50_share'][0]:.1%}")
    palma = summary["palma_ratio"][0]
    c4.metric("Palma ratio", f"{palma:.2f}" if np.isfinite(palma) else "∞")

    curve = ineq.lorenz_curve(values)
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode="lines", name="Perfect equality",
                              line=dict(dash="dash", color="gray")))
    fig.add_trace(go.Scatter(x=curve["population_share"], y=curve["value_share"],
                              mode="lines", name="Lorenz curve", fill="tonexty"))
    fig.update_layout(
        title="Lorenz curve",
        xaxis_title="Cumulative population share",
        yaxis_title="Cumulative value share",
        height=450,
    )
    st.plotly_chart(fig, use_container_width=True)

    with st.expander("What does each measure mean?"):
        st.markdown(
            "- **Gini coefficient**: 0 = perfect equality, closer to 1 = more "
            "concentrated. Sensitive to the *middle* of the distribution.\n"
            "- **Palma ratio**: top-10% share ÷ bottom-40% share. Deliberately "
            "ignores the 'stable middle' and focuses on the tails.\n"
            "- **Lorenz curve**: how far the actual cumulative distribution "
            "bows away from the 45° line of perfect equality.\n\n"
            "See `docs/METHODOLOGY.md` for exact formulas and limitations — "
            "inequality measurement is sensitive to top-tail underreporting, "
            "unit of analysis (household vs. individual), and whether income "
            "or wealth is measured."
        )

with tab_wealth:
    st.subheader("Composition effect: same savings, different asset mix")
    st.caption(
        "Two households save the same amount every year. One holds mostly "
        "property and bank deposits; the other holds more equities. This is "
        "a **deterministic model** — it shows what fixed assumptions imply, "
        "not a forecast."
    )

    col1, col2 = st.columns(2)
    with col1:
        contribution = st.number_input("Annual contribution (₹)", 10_000, 10_000_000, 100_000, step=10_000)
        years = st.slider("Horizon (years)", 1, 40, 20)
        inflation = st.slider("Assumed inflation (%)", 0.0, 12.0, 5.0) / 100
    with col2:
        st.markdown("**Household A allocation** (editable)")
        alloc_a = {}
        for k in wealth.ASSET_KEYS:
            alloc_a[k] = st.slider(
                f"A: {wealth.ASSET_LABELS[k]}", 0, 100,
                int(wealth.DEFAULT_ALLOCATION[k] * 100), key=f"a_{k}",
            )

    alloc_b = {"property": 10, "gold": 5, "equities": 65, "gov_bonds": 10, "bank_deposits": 8, "cash": 2}

    res_a = wealth.composition_effect(contribution, years, alloc_a, inflation=inflation)
    res_b = wealth.composition_effect(contribution, years, alloc_b, inflation=inflation)

    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(x=res_a.years, y=res_a.real_wealth, name="Household A (your mix)"))
    fig2.add_trace(go.Scatter(x=res_b.years, y=res_b.real_wealth, name="Household B (equity-heavy, fixed)"))
    fig2.update_layout(
        title="Real (inflation-adjusted) wealth over time",
        xaxis_title="Year", yaxis_title="₹ (today's purchasing power)", height=450,
    )
    st.plotly_chart(fig2, use_container_width=True)

    gap = res_b.real_wealth[-1] - res_a.real_wealth[-1]
    st.metric(
        f"Gap after {years} years (same contributions, different allocation)",
        f"₹{gap:,.0f}",
    )
    st.caption(
        "Both households contributed exactly the same amount every year. "
        "The entire gap above comes from *where* the money was held, not "
        "how much was earned or saved — this is the 'composition effect.'"
    )

st.divider()
st.caption(
    "Part of a nine-project open-source portfolio exploring economics, "
    "finance and Indian economic data. See the root README for the full set."
)
