"""India Housing Affordability Index — interactive demo.

Pick a city (synthetic baseline) or enter custom numbers, edit the
financing assumptions, and see EMI, price-to-income, mortgage-payment-to-
income, loan-to-value, down-payment savings horizon and interest burden
computed live via `housing_affordability.metrics`.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import plotly.graph_objects as go
import streamlit as st

from housing_affordability.data_loader import CITY_NAMES, load_synthetic_city_baseline
from housing_affordability.metrics import affordability_summary

st.set_page_config(page_title="India Housing Affordability Index", page_icon="🏠", layout="wide")

st.title("🏠 India Housing Affordability Index")
st.caption(
    "A home-ownership affordability calculator — EMI, price-to-income, "
    "mortgage-payment-to-income, loan-to-value, and down-payment savings "
    "horizon — demonstrated on a synthetic per-city baseline."
)

st.warning(
    "⚠️ **SYNTHETIC DATA**: the city baseline values below (house price, "
    "household income) are illustrative, deterministically generated by "
    "`examples/generate_synthetic_city_housing.py`. They are **not** real "
    "market statistics. Only their broad relative ordering across cities "
    "(e.g. Mumbai and Delhi NCR least affordable, Kolkata and Ahmedabad "
    "more affordable among these eight) reflects commonly-reported "
    "qualitative patterns — every number is a stand-in for demonstration. "
    "See `docs/DATA_SOURCES.md` for where to get real data."
)

baseline_df = load_synthetic_city_baseline().set_index("city")

st.sidebar.header("Scenario inputs")
city = st.sidebar.selectbox("City (synthetic baseline)", ["Custom"] + CITY_NAMES, index=1)

if city != "Custom":
    row = baseline_df.loc[city]
    default_price = float(row["synthetic_house_price_inr"])
    default_income = float(row["synthetic_annual_household_income_inr"])
else:
    default_price = 8_000_000.0
    default_income = 1_500_000.0

house_price = st.sidebar.number_input(
    "House price (INR)", min_value=100_000.0, max_value=200_000_000.0, value=default_price, step=100_000.0
)
annual_income = st.sidebar.number_input(
    "Annual household income (INR)",
    min_value=50_000.0,
    max_value=50_000_000.0,
    value=default_income,
    step=50_000.0,
)
down_payment_pct = st.sidebar.slider("Down payment (%)", 0, 100, 20) / 100
mortgage_rate = st.sidebar.slider("Mortgage interest rate (% p.a.)", 0.0, 18.0, 8.5) / 100
loan_years = st.sidebar.slider("Loan tenure (years)", 1, 30, 20)
savings_rate_pct = st.sidebar.slider(
    "Assumed annual savings toward down payment (% of income)", 1, 60, 20
)

try:
    summary = affordability_summary(
        house_price=house_price,
        annual_household_income=annual_income,
        down_payment_pct=down_payment_pct,
        annual_interest_rate=mortgage_rate,
        loan_years=loan_years,
        annual_savings_for_down_payment=(savings_rate_pct / 100) * annual_income,
        city=city,
    )
except ValueError as exc:
    st.error(str(exc))
    st.stop()

st.subheader(f"Affordability snapshot — {city}")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Price-to-income ratio", f"{summary.price_to_income:.2f}x")
c2.metric("Monthly EMI", f"₹{summary.monthly_emi:,.0f}")
c3.metric("EMI-to-income ratio", f"{summary.mortgage_payment_to_income:.1%}")
c4.metric("Loan-to-value", f"{summary.loan_to_value:.0%}")

c5, c6, c7, c8 = st.columns(4)
c5.metric("Down payment needed", f"₹{summary.down_payment_amount:,.0f}")
c6.metric("Years to save down payment", f"{summary.years_to_save_down_payment:.1f}")
c7.metric("Total interest over loan life", f"₹{summary.total_interest:,.0f}")
c8.metric("Interest burden", f"{summary.interest_burden:.1%}" if summary.loan_amount > 0 else "—")

col_left, col_right = st.columns(2)

with col_left:
    fig_income = go.Figure()
    fig_income.add_trace(
        go.Bar(
            x=["Monthly income"],
            y=[summary.monthly_income],
            name="Monthly income",
            marker_color="#4C78A8",
        )
    )
    fig_income.add_trace(
        go.Bar(
            x=["Monthly income"],
            y=[summary.monthly_emi],
            name="EMI",
            marker_color="#E45756",
        )
    )
    fig_income.update_layout(
        title="Monthly EMI vs. monthly income",
        barmode="overlay",
        yaxis_title="INR / month",
        height=420,
    )
    st.plotly_chart(fig_income, use_container_width=True)

with col_right:
    if summary.loan_amount > 0:
        fig_split = go.Figure(
            data=[
                go.Pie(
                    labels=["Principal", "Total interest"],
                    values=[summary.loan_amount, summary.total_interest],
                    hole=0.45,
                    marker_colors=["#4C78A8", "#F2A43B"],
                )
            ]
        )
        fig_split.update_layout(title="Total repayment: principal vs. interest", height=420)
        st.plotly_chart(fig_split, use_container_width=True)
    else:
        st.info("100% down payment selected — no loan, so there is no principal/interest split to show.")

with st.expander("What do these ratios mean?"):
    st.markdown(
        "- **Price-to-income ratio**: house price ÷ annual household income. "
        "A common rule of thumb treats ≤3x as affordable and ≥5x as "
        "severely unaffordable, but it ignores financing terms entirely.\n"
        "- **EMI-to-income ratio** (mortgage-payment-to-income): share of "
        "monthly income going to the loan instalment. Indian lenders "
        "commonly cap total EMI obligations around 40-50% of take-home "
        "income.\n"
        "- **Loan-to-value**: share of the house price financed by debt "
        "rather than the down payment.\n"
        "- **Interest burden**: share of total repayments that is interest "
        "rather than principal — rises with rate *and* with tenure.\n\n"
        "See `docs/METHODOLOGY.md` for exact formulas, and the **Scenario "
        "Projection** and **City Comparison** pages in the sidebar for how "
        "these evolve over time and across cities."
    )

st.divider()
st.caption(
    "Part of a nine-project open-source portfolio exploring economics, "
    "finance and Indian economic data. See the root README for the full set."
)
